baseURL = 'https://microsoma0.github.io/'
locale = 'ru-ru'
title = 'microsoma | C++ Gamedev'
theme = 're-terminal'

[params]
  themeColor = "orange"

  contentTypeName = "posts"
  showLanguageSelector = true

  fullWidthTheme = true
  Toc = true
  logo.logoText = "microsoma"

  author = "microsoma"
  description = "C++ Gamedev (love graphics)"

[[params.social]]
  icon = "github"
  name = "Github"
  url = "https://github.com/microsoma0"

[languages]
  [languages.en]
  [languages.en.params]
    label = "English"
    locale = "en-us"
    title = "microsoma"
    subtitle = "C++ Gamedev"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

[languages.en.menu]
  [[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[languages.en.menu.main]]
    identifier = "showcase"
    name = "Showcase"
    url = "/showcase"



[languages.ru]
  [languages.ru.params]
    label = "Русский"
    locale = "ru-ru"
    title = "microsoma"
    subtitle = "C++ Gamedev"
    menuMore = "Показать ещё"
    readMore = "Читать ещё"
    readOtherPosts = "Другие записи"
    newerPosts = "Новые записи"
    olderPosts = "Старые записи"
    missingContentMessage = "Запись не найдена..."
    missingBackButtonLabel = "Назад на домашнюю страницу"
    minuteReadingTime = "минут"
    words = "слов"

[languages.ru.menu]
  [[languages.ru.menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[languages.ru.menu.main]]
    identifier = "showcase"
    name = "Showcase"
    url = "/showcase"
